#!/usr/bin/env bash
set -euo pipefail

# Build/push shared Linux CI images from already-prepared kernel SDKs.
#
# Run from the esp-hosted-linux repository root on espdevpool1.
#
# Required:
#   docker login gitlab.espressif.cn:5050
#
# Optional:
#   SDK_ROOT=/srv/esp-hosted-ci/kernel-sdk
#   REGISTRY_IMAGE=gitlab.espressif.cn:5050/wireless/esp-hosted-linux
#   IMAGE_REV=1

ROOT="$(git rev-parse --show-toplevel)"
SDK_ROOT="${SDK_ROOT:-/srv/esp-hosted-ci/kernel-sdk}"
REGISTRY_IMAGE="${REGISTRY_IMAGE:-gitlab.espressif.cn:5050/wireless/esp-hosted-linux}"
IMAGE_REV="${IMAGE_REV:-1}"
TABLE="${ROOT}/.gitlab/ci/kernel-sdk/kernels.tsv"
BASE_DOCKER_DIR="${ROOT}/.gitlab/ci/docker/linux-base"
KERNEL_DOCKERFILE="${ROOT}/.gitlab/ci/docker/linux-kernel/Dockerfile"
OUTPUT="${ROOT}/.gitlab/ci/linux-images.yml"

declare -A BASE_IMAGES=(
    [gcc9]="${REGISTRY_IMAGE}/ci/linux-base:gcc9-${IMAGE_REV}"
    [gcc11]="${REGISTRY_IMAGE}/ci/linux-base:gcc11-${IMAGE_REV}"
    [gcc13]="${REGISTRY_IMAGE}/ci/linux-base:gcc13-${IMAGE_REV}"
)

# Preflight every SDK before building/pushing anything.
preflight_missing=0
while IFS=$'\t' read -r key version toolchain; do
    [[ -z "${key}" || "${key}" == \#* ]] && continue
    sdk="${SDK_ROOT}/${version}"
    if [[ ! -f "${sdk}/Makefile" || ! -s "${sdk}/.config" || ! -s "${sdk}/Module.symvers" ]]; then
        echo "MISSING/INCOMPLETE: ${sdk}" >&2
        preflight_missing=1
        continue
    fi
    actual="$(make -s -C "${sdk}" kernelversion)"
    if [[ "${actual}" != "${version}" ]]; then
        echo "WRONG VERSION: ${sdk} reports ${actual}, expected ${version}" >&2
        preflight_missing=1
    fi
done < "${TABLE}"

if (( preflight_missing != 0 )); then
    echo "ERROR: fix/prepare the SDK set before publishing images." >&2
    exit 2
fi

build_base() {
    local tc="$1"
    local image="${BASE_IMAGES[$tc]}"

    echo "=== Building ${image} ==="
    docker build \
        --pull \
        -f "${BASE_DOCKER_DIR}/Dockerfile.${tc}" \
        -t "${image}" \
        "${BASE_DOCKER_DIR}"

    docker push "${image}"
}

for tc in gcc9 gcc11 gcc13; do
    build_base "${tc}"
done

tmp="$(mktemp -d)"
trap 'rm -rf "${tmp}"' EXIT

declare -a yaml_lines
missing=0

while IFS=$'\t' read -r key version toolchain; do
    [[ -z "${key}" || "${key}" == \#* ]] && continue

    sdk="${SDK_ROOT}/${version}"
    if [[ ! -f "${sdk}/Makefile" || ! -s "${sdk}/.config" || ! -s "${sdk}/Module.symvers" ]]; then
        echo "ERROR: prepared SDK missing/incomplete: ${sdk}" >&2
        missing=1
        continue
    fi

    actual="$(make -s -C "${sdk}" kernelversion)"
    [[ "${actual}" == "${version}" ]] || {
        echo "ERROR: ${sdk} reports kernel ${actual}, expected ${version}" >&2
        exit 1
    }

    context="${tmp}/${key}"
    mkdir -p "${context}/sdk"
    rsync -a --delete "${sdk}/" "${context}/sdk/"

    image="${REGISTRY_IMAGE}/ci/linux-kernel:${version}-${toolchain}-${IMAGE_REV}"
    base="${BASE_IMAGES[$toolchain]}"

    echo "=== Building ${image} ==="
    docker build \
        --build-arg "BASE_IMAGE=${base}" \
        --build-arg "KERNEL_VERSION=${version}" \
        -f "${KERNEL_DOCKERFILE}" \
        -t "${image}" \
        "${context}"

    echo "=== Local smoke test ${version} ==="
    docker run --rm "${image}" bash -lc '
        set -e
        test -s "$KERNEL/.config"
        test -s "$KERNEL/Module.symvers"
        echo "kernel=$(make -s -C "$KERNEL" kernelversion)"
        echo "gcc=$(gcc --version | head -1)"
    '

    docker push "${image}"

    # After push, RepoDigests contains the immutable registry digest.
    digest_ref="$(docker inspect "${image}" --format='{{index .RepoDigests 0}}')"
    [[ "${digest_ref}" == *@sha256:* ]] || {
        echo "ERROR: no pushed digest for ${image}" >&2
        exit 1
    }

    var_name="LINUX_IMAGE_${key#K}"
    # Convert e.g. 49 -> 4_9, 414 -> 4_14, 510 -> 5_10, etc.
    case "${key}" in
        K49)  var_name=LINUX_IMAGE_4_9 ;;
        K414) var_name=LINUX_IMAGE_4_14 ;;
        K419) var_name=LINUX_IMAGE_4_19 ;;
        K54)  var_name=LINUX_IMAGE_5_4 ;;
        K510) var_name=LINUX_IMAGE_5_10 ;;
        K515) var_name=LINUX_IMAGE_5_15 ;;
        K61)  var_name=LINUX_IMAGE_6_1 ;;
        K66)  var_name=LINUX_IMAGE_6_6 ;;
        K612) var_name=LINUX_IMAGE_6_12 ;;
        K618) var_name=LINUX_IMAGE_6_18 ;;
        K72)  var_name=LINUX_IMAGE_7_2 ;;
    esac

    yaml_lines+=("  ${var_name}: \"${digest_ref}\"")
done < "${TABLE}"

if (( missing != 0 )); then
    echo
    echo "One or more SDKs were missing. No CI image reference file was changed." >&2
    exit 2
fi

{
    echo "# Generated by .gitlab/ci/kernel-sdk/publish-linux-images.sh"
    echo "# Do not hand-edit image digests."
    echo "variables:"
    printf '%s\n' "${yaml_lines[@]}"
} > "${OUTPUT}"

echo
echo "=== Wrote digest-pinned ${OUTPUT} ==="
cat "${OUTPUT}"
