FROM ubuntu:24.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    gcc-13 \
    g++-13 \
    clang-18 \
    llvm-18 \
    lld-18 \
    make \
    bc \
    bison \
    flex \
    libssl-dev \
    libelf-dev \
    kmod \
    cpio \
    rsync \
    python3 \
    ca-certificates \
    git \
    perl \
    sparse \
    shellcheck \
    ccache \
    && rm -rf /var/lib/apt/lists/*

RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100 && \
    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 100 && \
    update-alternatives --install /usr/bin/clang clang /usr/bin/clang-18 100 && \
    update-alternatives --install /usr/bin/ld.lld ld.lld /usr/bin/ld.lld-18 100

ENV CCACHE_COMPILERCHECK=content
ENV CCACHE_NOHASHDIR=true

CMD ["/bin/bash"]
